routes/admin.php
<?php

Route::get('/', ['as' => 'dashboard.index', 'uses' => 'DashboardController@getIndex']);
Route::resource('article', 'ArticleController');
Route::resource('category', 'CategoryController');
Route::resource('page', 'PageController');
Route::resource('user', 'UserController');

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

Route::get('/', ['as' => 'root', 'uses' => 'PageController@getIndex']);
Route::get('a/{aSlug}', ['as' => 'article', 'uses' => 'PageController@getArticle']);
Route::get('p/{pSlug}', ['as' => 'page', 'uses' => 'PageController@getPage']);
Route::get('c/{cSlug}', ['as' => 'category', 'uses' => 'PageController@getCategory']);
Route::get('sitemap.xml', ['as' => 'sitemap', 'uses' => 'PageController@getSitemap']);

app/Models/Article.php
<?php

namespace App\Models;

use App\Base\SluggableModel;

class Article extends SluggableModel
{
    /**
     * Carbon instance fields
     *
     * @var array
     */
    protected $dates = ['published_at'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function category(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    /**
     * @param $query
     *
     * @return mixed
     */
    public function scopePublished($query)
    {
        return $query->where('published_at', '<=', now())->orderBy('published_at', 'desc');
    }

    /**
     * @return string
     */
    public function getLocalizedPublishedAtAttribute(): string
    {
        return $this->published_at->formatLocalized('%e %B %Y');
    }

    /**
     * @return string
     */
    public function getLinkAttribute(): string
    {
        return route('article', ['aSlug' => $this->slug]);
    }
}

app/Models/Page.php
<?php

namespace App\Models;

use App\Base\SluggableModel;

class Page extends SluggableModel
{
    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     */
    public function parent(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(__CLASS__);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function children(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany(__CLASS__, 'parent_id', 'id');
    }

    /**
     * @return string
     */
    public function getLinkAttribute(): string
    {
        return route('page', ['pSlug' => $this->slug]);
    }
}

resources/views/partials/app/articles.blade.php
<div class="columns is-multiline">
    @foreach ($articles as $article)
        <div class="column is-12">
            <div class="columns is-vcentered">
                <div class="column is-9">
                    <h2 class="title"><a class="has-text-grey-dark" href="{{ $article->link }}">{{ $article->title }}</a></h2>
                </div>
                <div class="column is-3 has-text-right-desktop">
                    <a href="{{ $article->category->link }}" class="button is-default">{{ $article->category->title }}</a>
                </div>
            </div>
            <div class="level"></div>
            <div class="content">
                <p>{{ getNWords($article->content, 50) }}</p>
            </div>
            <div class="columns is-vcentered">
                <div class="column is-9">
                    <a class="button is-link" href="{{ $article->link }}">{{ __('app.read_more') }}</a>
                </div>
                <div class="column is-3 has-text-right-desktop">
                    <p class="has-text-grey">{{ $article->localized_published_at }}</p>
                </div>
            </div>
        </div>
    @endforeach
    @if ($articles->total() > $articles->count())
        <div class="column is-12">
            {!! $articles->appends(request()->except('page'))->links() !!}
        </div>
    @endif
</div>

resources/views/partials/app/breadcrumbs.blade.php
<nav class="breadcrumb" aria-label="breadcrumbs">
    <ul>
        <li><a href="{{ route('root') }}">{{ getTitle() }}</a></li>
        @if (isset($object->parent))
            <li><a href="{{ $object->parent->link }}">{{ $object->parent->title }}</a></li>
        @elseif (isset($object->category))
            <li><a href="{{ $object->category->link }}">{{ $object->category->title }}</a></li>
        @endif
        <li class="is-active"><a href="{{ url()->current() }}}" aria-current="page">{{ $object->title }}</a></li>
    </ul>
</nav>

resources/views/partials/app/content.blade.php
<section class="section">
    <div class="container">
        <div class="columns">
            <div class="column is-12">
                @include('partials.app.breadcrumbs')
                <div class="content">{!! $content !!}</div>
            </div>
        </div>
    </div>
</section>

resources/views/partials/app/errors.blade.php
@if (isset($errors) && count($errors) > 0)
    @foreach ($errors->all() as $error)
        <div class="notification response-notification is-warning has-text-centered">
            <span class="icon">{!! icon('alert-circle') !!}</span>
            <span class="text">{{ $error }}</span>
        </div>
    @endforeach
@endif
@if (session()->has('error'))
    <div class="notification response-notification is-warning has-text-centered">
        <span class="icon">{!! icon('alert-circle') !!}</span>
        <span class="text">{{ session()->get('error') }}</span>
    </div>
@endif
@if (session()->has('success'))
    <div class="notification response-notification is-success has-text-centered">
        <span class="icon">{!! icon('info') !!}</span>
        <span class="text">{{ session()->get('success') }}</span>
    </div>
@endif

resources/views/partials/app/footer.blade.php
<footer class="footer">
    <div class="container">
        <div class="content">
            <div class="columns">
                <div class="column is-3">
                    <p class="title is-5">{{ __('app.footer.share') }}</p>
                    @foreach (['facebook', 'twitter'] as $social)
                        <p>
                            <a href="@yield($social)" rel="nofollow noopener" target="_blank">
                                <span class="icon">{!! icon($social) !!}</span>
                                <span class="text">{{ ucfirst($social) }}</span>
                            </a>
                        </p>
                    @endforeach
                </div>
                <div class="column is-3">
                    <p class="title is-5">{{ __('app.footer.latest') }}</p>
                    @foreach (getFooterArticles() as $article)
                        <p><a href="{{ $article->link }}">{{ $article->title }}</a></p>
                    @endforeach
                </div>
                <div class="column is-6">
                    <p class="title is-5">{{ __('app.footer.about') }}</p>
                    <p>{{ __('app.footer.text') }}</p>
                    <a href="{{ __('app.footer.url') }}">{{ __('app.footer.url') }}</a>
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/partials/app/hero.blade.php
<section class="hero is-primary {{ $class ?? '' }}">
    <div class="hero-body">
        <div class="container">
            <div class="columns">
                <div class="column is-12">
                    <h1 class="title">{{ $title }}</h1>
                    <h2 class="subtitle">{{ $description }}</h2>
                </div>
            </div>
        </div>
    </div>
</section>
@include('partials.app.errors')

resources/views/partials/app/nav.blade.php
<nav class="navbar is-light">
    <div class="container">
        <div class="navbar-brand">
            <a class="navbar-item" href="{{ route('root') }}">
                <img src="{{ asset(config('settings.logo')) }}" alt="{{ config('settings.site_title') }}">
            </a>
            <div id="toggle-menu" class="navbar-burger burger">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="menu" class="navbar-menu">
            <div class="navbar-start">
                @foreach (getMenu() as $p)
                    @if ($p->children->count() > 0)
                        <div class="navbar-item has-dropdown is-hoverable">
                            <div class="navbar-link">
                                <a class="navbar-item {{ active($p) }}" href="{{ $p->link }}">
                                    {{ $p->title }}
                                </a>
                            </div>
                            <div class="navbar-dropdown">
                                @foreach ($p->children as $child)
                                    <a class="navbar-item {{ active($child) }}" href="{{ $child->link }}">
                                        {{ $child->title }}
                                    </a>
                                @endforeach
                            </div>
                        </div>
                    @else
                        <a class="navbar-item" href="{{ $p->link }}">
                            {{ $p->title }}
                        </a>
                    @endif
                @endforeach
            </div>
            <div class="navbar-end">
                <div class="navbar-item">
                    <div class="field is-grouped">
                        <p class="control">
                            <a target="_blank" rel="noopener noreferrer" href="@yield('facebook')" class="button button-facebook">
                                <span class="icon">{!! icon('facebook') !!}</span>
                                <span>{{ __('app.buttons.share') }}</span>
                            </a>
                        </p>
                        <p class="control">
                            <a target="_blank" rel="noopener noreferrer" href="@yield('twitter')" class="button button-twitter">
                                <span class="icon">{!! icon('twitter') !!}</span>
                                <span>{{ __('app.buttons.tweet') }}</span>
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

resources/views/partials/app/sections.blade.php
@section('title'){{ $title ?? getTitle() }}@endsection
@section('description'){{ $description ?? getDescription() }}@endsection
@section('image'){{ $image ?? getImage() }}@endsection
@section('facebook'){{ getFacebookShareLink($currentUrl ?? request()->url(), $title ?? getTitle()) }}@endsection
@section('twitter'){{ getTwitterShareLink($currentUrl ?? request()->url(), $title ?? getTitle()) }}@endsection
@section('robots'){{ $robots ?? getRobots() }}@endsection